#-------------------------------
# Site Settings

title: OctoFi
logo: #'/images/logo.png'
description: All-in-one DeFi and NFT with cashbacks

menu__settings:
  menu__items:
    - title: 'About'
      url: '/dyor'
    - title: 'Manifesto'
      url: '/manifesto'
    - title: 'Project'
      submenu:
      - url: '/roadmap'
        title: 'Roadmap'
      - url: '/changelog'
        title: 'Changes'
      - external_url: 'https://github.com/octofi'
        title: 'GitHub'
    - title: 'Support'
      submenu:
      - external_url: 'https://t.me/OctoFi'
        title: 'Telegram'
      - external_url: 'https://den.octo.fi'
        title: 'Forums'
      - external_url: 'https://links.octo.fi'
        title: 'Links'
    - title: 'Blog'
      url: '/blog'
# Call to action button
cta__button__text: Launch dApp
cta__button__url: 'https://app.octo.fi'

# Add global cover image (This field adds a background to the top and bottom of the site.)
cover__image: '/images/37.jpg'


#-------------------------------
# Author Settings

author:
  name: Dr. Octavius
  title: All-in-one DeFi and NFT with cashbacks
  bio: OctoFi gives you cash back when you transact with trusted DeFi and NFT marketplaces, across multiple blockchains, through our all-in-one <span class="text-span post__content"><a href="https://app.octo.fi" target="_blank">dApp</a></span> or browser-plugin <span class="text-span post__content"><a href="/dyor#wallet">Wallet</a></span>.
  image: '/images/octofi-dapp.png'
  avatar: '/images/avatar.jpg'
  button__text: Launch dApp
  button__url: 'https://app.octo.fi'
  small__button__text: Learn more
  small__button__url: '/dyor'


#-------------------------------
# Projects Settings

projects__settings:
  projects__title: Referral <span class="text-span">partners</span> # Add a 'text-span' class to highlight text.
  projects__description: We get paid commission when you transact with our partners, through our <span class="text-span post__content"><a href="//app.octo.fi" target="_blank">dApp</a></span> or directly when using our <span class="text-span post__content"><a href="/dyor#wallet">Wallet</a></span>. 40% goes to you. 60% to <span class="text-span post__content"><a href="/dyor#token">token</a></span> holders.
  
  

#-------------------------------
# Team Settings

team__settings:
  team__title: The <span class="text-span">Octagon</span> # Add a 'text-span' class to highlight text.
  team__description: Eight members were elected as <span class="text-span post__content"><a href="https://gnosis-safe.io/app/#/safes/0xcCF04146399214EB7813Ab45B50d004c5b254784/balances" target="_blank">treasury multisig</a></span> key holders. An expert advisor, community secretary, and co-founders, OG and Octavius support them.
  
  

#-------------------------------
# Testimonials Section

testimonial__title: Team <span class="text-span">members</span> # Add a 'text-span' class to highlight text.


testimonial-items:
  - name: "Dr. Octavius"
    image: "/images/avatar.jpg"
    designation : "Co-Founder"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  - name: "Dr. Octavius"
    image: "/images/avatar.jpg"
    designation : "Co-Founder"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  - name: "Dr. Octavius"
    image: "/images/avatar.jpg"
    designation : "Co-Founder"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  - name: "Dr. Octavius"
    image: "/images/avatar.jpg"
    designation : "Co-Founder"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."


#-------------------------------
# Blog Section

blog__settings:
  blog__title: Recent <span class="text-span">posts</span> # Add a 'text-span' class to highlight text.
  blog__description:


#-------------------------------
# CTA Settings
calltoaction__settings:
  calltoaction__title: <span class="text-span">Free Crypto.</span> Octomatically.
  calltoaction__button__text: Launch dApp 
  calltoaction__button__url: 'https://app.octo.fi'


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: UA-175900160-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Footer Settings
# Social Links
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/octofinance"}
- {icon: "ion-logo-github", link: "https://github.com/octofi"}
- {icon: "ion-logo-youtube", link: "https://www.youtube.com/channel/UCQ8TelmjLpFKQAsZCXIs5Tw"}
